services:
  - type: worker
    name: esimbot-worker
    env: python
    buildCommand: chmod +x install_deps.sh && ./install_deps.sh
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: AIRALO_API_KEY
        sync: false
    autoDeploy: true 