services:
  - type: worker
    name: esimbot-worker
    env: python
    buildCommand: |
      # Update pip and setuptools
      pip install --upgrade pip setuptools wheel

      # Downgrade httpx to a version compatible with solana
      pip install httpx==0.23.3

      # Install core dependencies
      pip install python-telegram-bot==20.8 python-dotenv==1.0.1 requests==2.31.0 aiohttp==3.9.3 certifi==2024.2.2 solders==0.19.0 base58==2.1.1

      # Manually download, unpack and install solana package
      echo "Installing solana package directly from GitHub..."
      mkdir -p /tmp/solana-py
      curl -L https://github.com/michaelhly/solana-py/archive/refs/tags/v0.31.0.tar.gz | tar -xz -C /tmp/solana-py --strip-components=1
      cd /tmp/solana-py
      
      # Edit the pyproject.toml to fix the httpx dependency
      sed -i 's/httpx>=0.23.0,<0.24.0/httpx==0.23.3/g' pyproject.toml
      
      # Install the package
      pip install -e .
      cd -
      
      # Verify installation
      python -c "import solana; print(f'Successfully imported solana v{solana.__version__}')"
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: AIRALO_API_KEY
        sync: false
    autoDeploy: true 