services:
  - type: web
    name: esimbot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install httpx==0.23.3
      pip install python-dotenv==1.0.1 requests==2.31.0 aiohttp==3.9.3 certifi==2024.2.2 solders==0.19.0 base58==2.1.1
      pip install --no-deps solana==0.31.0
      python -c "import solana; print(f'Successfully imported solana')"
      pip install --upgrade httpx~=0.26.0
      pip install python-telegram-bot==20.8
      echo "Build completed successfully"
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: AIRALO_CLIENT_ID
        sync: false
      - key: AIRALO_CLIENT_SECRET
        sync: false
    autoDeploy: true 